const BUCKET_NAME = process.env.BUCKET_NAME
const BUCKET_NAME_NEW_BACS = process.env.BUCKET_NAME_NEW_BACS
const BUCKET_NAME_ARCHIVED_BACS = process.env.BUCKET_NAME_ARCHIVED_BACS
const IAM_USER_KEY = process.env.IAM_USER_KEY
const IAM_USER_SECRET = process.env.IAM_USER_SECRET

module.exports = { BUCKET_NAME, IAM_USER_KEY, IAM_USER_SECRET, BUCKET_NAME_NEW_BACS, BUCKET_NAME_ARCHIVED_BACS} 