const BUCKET_NAME = ENV['BUCKET_NAME']
const BUCKET_NAME_NEW_BACS = ENV['BUCKET_NAME_NEW_BACS']
const BUCKET_NAME_ARCHIVED_BACS = ENV['BUCKET_NAME_ARCHIVED_BACS']
const IAM_USER_KEY = ENV['IAM_USER_KEY']
const IAM_USER_SECRET = ENV['IAM_USER_SECRET']

module.exports = { BUCKET_NAME, IAM_USER_KEY, IAM_USER_SECRET, BUCKET_NAME_NEW_BACS, BUCKET_NAME_ARCHIVED_BACS} 